import { fireEvent, render, screen } from '@testing-library/svelte';
import { beforeEach, expect, it, vi } from 'vitest';
import StagedInstaller from './StagedInstaller.svelte';
import { setup } from './setup';
const calls=vi.hoisted(()=>({stagedIso:vi.fn(),prepareBitLocker:vi.fn(),respondStagedReview:vi.fn(),cancel:vi.fn()}));
vi.mock('./setup',async importOriginal=>{
  const actual=await importOriginal<typeof import('./setup')>();
  const {writable}=await import('svelte/store');
  return {...actual,setup:{...writable({pending:false,snapshot:null}),...calls}};
});
const state=setup as typeof setup & {set:(value:unknown)=>void};
beforeEach(()=>{vi.clearAllMocks();state.set({pending:false,snapshot:null});});
it('shows nothing and does not elevate when no temporary installer exists',()=>{
  render(StagedInstaller,{recoveryOnly:true});
  expect(calls.stagedIso).not.toHaveBeenCalled();
  expect(screen.queryByRole('region',{name:'Temporary installer'})).not.toBeInTheDocument();
  expect(screen.queryByRole('button')).not.toBeInTheDocument();
});
it('binds boot and cleanup actions to the recorded operation',async()=>{
  const op={operationId:'11111111-1111-4111-8111-111111111111',status:'staged',diskNumber:0,temporaryBytes:8*1024**3,message:'Installer ready'};
  state.set({pending:false,snapshot:{status:'complete',stagedTesting:true,stagedIso:{operations:[op]}}});
  render(StagedInstaller,{recoveryOnly:true});
  await fireEvent.click(screen.getByRole('button',{name:'Start installer on next restart'}));
  expect(calls.stagedIso).toHaveBeenLastCalledWith('arm',null,op.operationId);
  await fireEvent.click(screen.getByRole('button',{name:'Remove temporary installer'}));
  expect(calls.stagedIso).toHaveBeenLastCalledWith('cleanup',null,op.operationId);
});
it('offers only reviewed cleanup for an incomplete copy',()=>{
  state.set({pending:false,snapshot:{status:'complete',stagedIso:{operations:[{operationId:'id',status:'copying',diskNumber:0,temporaryBytes:8*1024**3,message:'Interrupted'}]}}});
  render(StagedInstaller,{recoveryOnly:true});
  expect(screen.queryByRole('button',{name:'Start installer on next restart'})).not.toBeInTheDocument();
  expect(screen.getByRole('button',{name:'Remove temporary installer'})).toBeEnabled();
});
it('blocks overlapping operations',()=>{
  state.set({pending:false,snapshot:{status:'running'}});
  render(StagedInstaller);
  for(const button of screen.getAllByRole('button')) expect(button).toBeDisabled();
});
it('shows unreadable records while preserving valid recovery actions',async()=>{
  const op={operationId:'valid-record',status:'copying',diskNumber:0,temporaryBytes:8*1024**3,message:'Interrupted'};
  state.set({pending:false,snapshot:{status:'complete',stagedIso:{operations:[op],recordErrors:[{operationId:'incomplete-record',message:'Missing state.json'}]}}});
  render(StagedInstaller,{recoveryOnly:true});
  expect(screen.getByRole('alert')).toHaveTextContent('could not be identified safely');
  expect(screen.getByText('incomplete-record: Missing state.json')).toBeInTheDocument();
  expect(screen.getAllByRole('button',{name:'Remove temporary installer'})).toHaveLength(1);
  await fireEvent.click(screen.getByRole('button',{name:'Remove temporary installer'}));
  expect(calls.stagedIso).toHaveBeenLastCalledWith('cleanup',null,op.operationId);
});
it('allows real inspection only in a testing build with a verified ISO',async()=>{
  state.set({pending:false,snapshot:{status:'idle',stagedTesting:true}});
  const view=render(StagedInstaller,{sourceReady:false});
  expect(screen.getByRole('button',{name:'Check available space'})).toBeDisabled();
  await view.rerender({sourceReady:true});
  expect(screen.getByText('Test build · real disk changes')).toBeInTheDocument();
  await fireEvent.click(screen.getByRole('button',{name:'Check available space'}));
  expect(calls.stagedIso).toHaveBeenCalledWith('inspect');
});
it('prepares again only after reviewed cleanup completes',async()=>{
  const op={operationId:'id',status:'copying',diskNumber:0,temporaryBytes:8*1024**3};
  state.set({pending:false,snapshot:{status:'complete',stagedTesting:true,stagedRecovery:{operations:[op],recordErrors:[]}}});
  const prepareAgain=vi.fn();
  render(StagedInstaller,{recoveryOnly:true,sourceReady:true,prepareAgain});
  await fireEvent.click(screen.getByRole('button',{name:'Prepare again'}));
  expect(calls.stagedIso).toHaveBeenLastCalledWith('cleanup',null,'id');
  expect(prepareAgain).not.toHaveBeenCalled();
  state.set({pending:false,snapshot:{status:'complete',stagedTesting:true,stagedRecovery:{operations:[],recordErrors:[]},stagedIso:{operationId:'id',status:'cleaned'}}});
  await import('svelte').then(({tick})=>tick());
  expect(prepareAgain).toHaveBeenCalledOnce();
  expect(calls.stagedIso).toHaveBeenLastCalledWith('inspect');
});
const encrypted={diskNumber:0,diskUniqueId:'windows-disk',label:'Shrink partition 3',largestFreeAfterStagingBytes:0,target:{target_kind:'shrink',partition_number:3,partition_guid:'guid'},encryption:[{driveLetter:'C:',isOsVolume:true,conversionStatus:1,protectionStatus:1,lockStatus:0}]};
const free={diskNumber:1,diskUniqueId:'second-disk',label:'Unallocated space',largestFreeAfterStagingBytes:80*1024**3,target:{target_kind:'free',start_offset_bytes:1024**2}};
const inspected=()=>({pending:false,snapshot:{status:'complete',stagedTesting:true,stagedIso:{choices:[free,encrypted],blocked:[],temporaryBytes:8*1024**3,minimumLinuxBytes:32*1024**3}}});
const fullDisk={diskNumber:0,diskUniqueId:'windows-disk',diskSizeBytes:500*1024**3,unallocatedBytes:0,largestFreeBytes:0,regions:[{kind:'partition',partitionNumber:3,partitionGuid:'guid',offsetBytes:1024**2,sizeBytes:500*1024**3,label:'C:',fileSystem:'NTFS',freeBytes:100*1024**3,resizeState:'unchecked'}]};
it('keeps tiny gaps in the total while moving them out of the partition list',async()=>{
  const gap={kind:'free',offsetBytes:2*1024**2,sizeBytes:1024**2,label:'Unallocated space'};
  const withGap={...fullDisk,unallocatedBytes:1024**2,regions:[fullDisk.regions[0],gap]};
  state.set({pending:false,snapshot:{status:'complete',stagedTesting:true,stagedIso:{choices:[],blocked:[],disks:[withGap],minimumLinuxBytes:40*1024**3,temporaryBytes:8*1024**3}}});
  render(StagedInstaller,{sourceReady:true});
  await import('svelte').then(({tick})=>tick());
  expect(screen.getByText('1 MiB unallocated')).toBeInTheDocument();
  expect(screen.getByText('1 MiB in small alignment gaps')).toBeInTheDocument();
  expect(screen.queryByText('Unallocated space')).not.toBeInTheDocument();
});
it('explains a partition that cannot provide enough space without waiting for a shrink limit',async()=>{
  const scarce={...fullDisk,regions:[{...fullDisk.regions[0],freeBytes:1.9*1024**3,resizeState:'insufficient'}]};
  state.set({pending:false,snapshot:{status:'complete',stagedTesting:true,stagedIso:{choices:[],blocked:[],disks:[scarce],minimumLinuxBytes:40*1024**3,temporaryBytes:7.3*1024**3}}});
  render(StagedInstaller,{sourceReady:true});
  await import('svelte').then(({tick})=>tick());
  expect(screen.getByText('7.3 GiB needed')).toBeInTheDocument();
  expect(screen.getByText('5.4 GiB more unused space needed in this partition. Free up space in Windows, then refresh.')).toBeInTheDocument();
  expect(screen.queryByText('Checking Windows resize limit…')).not.toBeInTheDocument();
});
it('shows a full disk while Windows measures its resize limit',async()=>{
  state.set({pending:false,snapshot:{status:'running',stage:'inspecting',stagedTesting:true,stagedIso:{choices:[],blocked:[],disks:[fullDisk],minimumLinuxBytes:40*1024**3,temporaryBytes:8*1024**3}}});
  render(StagedInstaller,{sourceReady:true});
  await import('svelte').then(({tick})=>tick());
  expect(screen.getByRole('button',{name:/Disk 0/})).toHaveAttribute('aria-pressed','true');
  expect(screen.getByText('8.0 GiB needed')).toBeInTheDocument();
  expect(screen.getByText('0 MiB unallocated')).toBeInTheDocument();
  expect(screen.getByText('100.0 GiB unused inside this partition')).toBeInTheDocument();
  expect(screen.queryByRole('button',{name:'Review changes'})).not.toBeInTheDocument();
  expect(screen.getByText('Checking Windows resize limit…')).toBeInTheDocument();
  expect(calls.stagedIso).not.toHaveBeenCalled();
  state.set({pending:false,snapshot:{status:'complete',stagedTesting:true,stagedIso:{choices:[encrypted],blocked:[],disks:[{...fullDisk,regions:[{...fullDisk.regions[0],resizeState:'checked',maximumReleaseBytes:108*1024**3,reserveBytes:20*1024**3}]}],minimumLinuxBytes:40*1024**3,temporaryBytes:8*1024**3}}});
  await import('svelte').then(({tick})=>tick());
  expect(screen.getByRole('button',{name:'Review changes'})).toBeEnabled();
  await fireEvent.click(screen.getByRole('button',{name:'Review changes'}));
  expect(calls.stagedIso).toHaveBeenLastCalledWith('stage',{diskNumber:0,diskUniqueId:'windows-disk',target:encrypted.target,linuxBytes:64*1024**3});
});
it('keeps browsing available while measured limits arrive in one inspection',async()=>{
  const other={...fullDisk,diskNumber:1,diskUniqueId:'other-disk',regions:[{...fullDisk.regions[0],partitionGuid:'other-guid',label:'D:'}]};
  const base={choices:[],blocked:[],disks:[fullDisk,other],minimumLinuxBytes:40*1024**3,temporaryBytes:8*1024**3};
  state.set({pending:false,snapshot:{status:'running',stage:'inspecting',stagedTesting:true,stagedIso:base}});
  render(StagedInstaller,{sourceReady:true});
  await import('svelte').then(({tick})=>tick());
  expect(calls.stagedIso).not.toHaveBeenCalled();
  await fireEvent.click(screen.getByRole('button',{name:/Disk 1/}));
  expect(screen.getByText('100.0 GiB unused inside this partition')).toBeInTheDocument();
  state.set({pending:false,snapshot:{status:'running',stage:'analyzing-resize',stagedTesting:true,stagedIso:{...base,choices:[encrypted],disks:[{...fullDisk,regions:[{...fullDisk.regions[0],resizeState:'checked',maximumReleaseBytes:108*1024**3,reserveBytes:20*1024**3}]},other]}}});
  await import('svelte').then(({tick})=>tick());
  expect(calls.stagedIso).not.toHaveBeenCalled();
  await fireEvent.click(screen.getByRole('button',{name:/Disk 0/}));
  expect(screen.getByText(/Can release 108.0 GiB/)).toBeInTheDocument();
  expect(screen.getByRole('button',{name:'Review changes'})).toBeDisabled();
  state.set({pending:false,snapshot:{status:'complete',stage:'complete',stagedTesting:true,stagedIso:{...base,choices:[encrypted],disks:[{...fullDisk,regions:[{...fullDisk.regions[0],resizeState:'checked',maximumReleaseBytes:108*1024**3,reserveBytes:20*1024**3}]},{...other,regions:[{...other.regions[0],resizeState:'checked',maximumReleaseBytes:10*1024**3,reserveBytes:20*1024**3}]}]}}});
  await import('svelte').then(({tick})=>tick());
  expect(screen.getByText(/Can release 108.0 GiB/)).toBeInTheDocument();
  expect(screen.getByRole('button',{name:'Review changes'})).toBeEnabled();
  expect(calls.stagedIso).not.toHaveBeenCalled();
});
it('shows a measured shortfall without hiding the partitions or retry action',async()=>{
  state.set({pending:false,snapshot:{status:'complete',stagedTesting:true,stagedIso:{choices:[],blocked:[],disks:[{...fullDisk,regions:[{...fullDisk.regions[0],resizeState:'checked',maximumReleaseBytes:6*1024**3,reserveBytes:20*1024**3}]}],minimumLinuxBytes:32*1024**3,temporaryBytes:8*1024**3}}});
  render(StagedInstaller,{sourceReady:true});
  await fireEvent.click(screen.getByRole('button',{name:/Disk 0/}));
  expect(screen.getByText('2.0 GiB short of the space needed.')).toBeInTheDocument();
  expect(screen.getByRole('list',{name:'Partitions and unallocated space'})).toBeInTheDocument();
  expect(screen.getByRole('button',{name:'Recheck C:'})).toBeEnabled();
  expect(screen.queryByRole('button',{name:'Review changes'})).not.toBeInTheDocument();
});
it('allows encrypted space selection and defers suspension to confirmed staging',async()=>{
  state.set(inspected());
  render(StagedInstaller,{sourceReady:true});
  expect(screen.queryByRole('complementary',{name:'BitLocker preparation'})).not.toBeInTheDocument();
  await fireEvent.click(screen.getByRole('button',{name:/Disk 0/}));
  expect(screen.getByRole('complementary',{name:'BitLocker preparation'})).toBeInTheDocument();
  expect(screen.getByRole('button',{name:'Review changes'})).toBeEnabled();
  expect(screen.getByText('More space needed to finish')).toBeInTheDocument();
  expect(calls.prepareBitLocker).not.toHaveBeenCalled();
  await fireEvent.click(screen.getByRole('button',{name:'Review changes'}));
  expect(calls.stagedIso).toHaveBeenLastCalledWith('stage',{diskNumber:0,diskUniqueId:'windows-disk',target:encrypted.target});
  expect(calls.prepareBitLocker).not.toHaveBeenCalled();
  await fireEvent.click(screen.getByRole('button',{name:/Disk 1/}));
  expect(screen.queryByRole('complementary',{name:'BitLocker preparation'})).not.toBeInTheDocument();
  expect(screen.getByRole('button',{name:'Review changes'})).toBeEnabled();
});
it('preserves the chosen disk across status polling and submits the exact target',async()=>{
  state.set(inspected());
  render(StagedInstaller,{sourceReady:true});
  await fireEvent.click(screen.getByRole('button',{name:/Disk 1/}));
  state.set(structuredClone(inspected()));
  await import('svelte').then(({tick})=>tick());
  expect(screen.getByRole('button',{name:/Disk 1/})).toHaveAttribute('aria-pressed','true');
  await fireEvent.click(screen.getByRole('button',{name:'Review changes'}));
  expect(calls.stagedIso).toHaveBeenLastCalledWith('stage',{diskNumber:1,diskUniqueId:'second-disk',target:free.target});
});
it('keeps the selected disk after refresh',async()=>{
  state.set(inspected());
  render(StagedInstaller,{sourceReady:true});
  await fireEvent.click(screen.getByRole('button',{name:/Disk 0/}));
  await fireEvent.click(screen.getByRole('button',{name:'Refresh'}));
  expect(calls.stagedIso).toHaveBeenLastCalledWith('inspect');
  const cleared={...free,diskNumber:0,diskUniqueId:'windows-disk'};
  state.set({pending:false,snapshot:{status:'complete',stagedTesting:true,stagedIso:{choices:[cleared],blocked:[]}}});
  await import('svelte').then(({tick})=>tick());
  expect(screen.queryByRole('complementary',{name:'BitLocker preparation'})).not.toBeInTheDocument();
  expect(screen.getByRole('button',{name:/Disk 0/})).toHaveAttribute('aria-pressed','true');
  expect(screen.getByRole('button',{name:'Review changes'})).toBeEnabled();
});
it('invalidates destinations when refreshing fails',async()=>{
  state.set(inspected());
  render(StagedInstaller,{sourceReady:true});
  await fireEvent.click(screen.getByRole('button',{name:/Disk 1/}));
  await fireEvent.click(screen.getByRole('button',{name:'Refresh'}));
  state.set({...inspected(),error:'Inspection failed'});
  await import('svelte').then(({tick})=>tick());
  expect(screen.queryByRole('button',{name:'Review changes'})).not.toBeInTheDocument();
});
const measured=()=>({pending:false,snapshot:{status:'complete',stagedTesting:true,stagedIso:{choices:[encrypted],blocked:[],disks:[{...fullDisk,regions:[{...fullDisk.regions[0],resizeState:'checked',maximumReleaseBytes:108*1024**3,reserveBytes:20*1024**3}]}],minimumLinuxBytes:32*1024**3,temporaryBytes:8*1024**3,secureBoot:true}}});
it('keeps Windows with a chosen Omarchy size or replaces it later',async()=>{
  state.set(measured());
  render(StagedInstaller,{sourceReady:true});
  await import('svelte').then(({tick})=>tick());
  expect(screen.queryByText('More space needed to finish')).not.toBeInTheDocument();
  await fireEvent.input(screen.getByRole('spinbutton',{name:/Space for Omarchy/}),{target:{value:'40'}});
  await fireEvent.click(screen.getByRole('button',{name:'Review changes'}));
  expect(calls.stagedIso).toHaveBeenLastCalledWith('stage',{diskNumber:0,diskUniqueId:'windows-disk',target:encrypted.target,linuxBytes:40*1024**3});
  await fireEvent.click(screen.getByRole('radio',{name:'Replace Windows in the installer'}));
  expect(screen.getByText('More space needed to finish')).toBeInTheDocument();
  await fireEvent.click(screen.getByRole('button',{name:'Review changes'}));
  expect(calls.stagedIso).toHaveBeenLastCalledWith('stage',{diskNumber:0,diskUniqueId:'windows-disk',target:encrypted.target});
});
it('tells users to leave Secure Boot on until the installer is prepared',async()=>{
  state.set(measured());
  render(StagedInstaller,{sourceReady:true});
  await import('svelte').then(({tick})=>tick());
  expect(screen.getByText(/Secure Boot is on. Leave it on for now/)).toBeInTheDocument();
});
it('reviews the staging plan in the app before any disk change',async()=>{
  state.set({pending:false,snapshot:{...measured().snapshot,status:'running',stagedReview:{summary:'Prepare the installer on Disk 0?\n\nShrink C: from 500.0 to 428.0 GiB.'}}});
  render(StagedInstaller,{sourceReady:true});
  await import('svelte').then(({tick})=>tick());
  const review=screen.getByRole('region',{name:'Review changes'});
  expect(review).toHaveTextContent('Shrink C: from 500.0 to 428.0 GiB.');
  expect(screen.queryByRole('button',{name:'Review changes'})).not.toBeInTheDocument();
  await fireEvent.click(screen.getByRole('button',{name:'Cancel'}));
  expect(calls.respondStagedReview).toHaveBeenLastCalledWith(false);
  await fireEvent.click(screen.getByRole('button',{name:'Prepare installer'}));
  expect(calls.respondStagedReview).toHaveBeenLastCalledWith(true);
});
it('shows copy progress and offers to stop only while copying',async()=>{
  state.set({pending:false,snapshot:{status:'running',stage:'copying-installer',message:'Copying and verifying the installer...',bytes:2*1024**3,totalBytes:6*1024**3,cancelAvailable:true,cancelRequested:false,stagedTesting:true}});
  render(StagedInstaller,{sourceReady:true});
  expect(screen.getByRole('progressbar',{name:'Copying the installer'})).toHaveAttribute('value',String(2*1024**3));
  await fireEvent.click(screen.getByRole('button',{name:'Stop preparing'}));
  expect(calls.cancel).toHaveBeenCalledOnce();
});
it('lets the installer be selected again after a restart and restarts to firmware settings',async()=>{
  const op={operationId:'11111111-1111-4111-8111-111111111111',status:'boot-scheduled',diskNumber:0,temporaryBytes:8*1024**3,message:''};
  state.set({pending:false,snapshot:{status:'complete',stagedTesting:true,stagedIso:{operations:[op]}}});
  render(StagedInstaller,{recoveryOnly:true});
  expect(screen.getByText('Installer selected for a restart')).toBeInTheDocument();
  expect(screen.getByText('What happens next')).toBeInTheDocument();
  await fireEvent.click(screen.getByRole('button',{name:'Start installer again on next restart'}));
  expect(calls.stagedIso).toHaveBeenLastCalledWith('arm',null,op.operationId);
  await fireEvent.click(screen.getByRole('button',{name:'Restart to firmware settings'}));
  expect(calls.stagedIso).toHaveBeenLastCalledWith('firmware',null,op.operationId);
});
