<script lang="ts">
  import { Archive, CheckCircle2, Download, FileText, LifeBuoy, MoreHorizontal, ShieldCheck } from 'lucide-svelte';
  import FlowHeader from '../lib/FlowHeader.svelte';
  import ActionButton from '../lib/ActionButton.svelte';
  export let openPlan: (title: string) => void;
</script>

<div class="flow-page">
  <FlowHeader eyebrow="Manage" title="Everything Omarchy Installer owns." description="Review completed operations, cached images, provider health, and redacted diagnostics. Resources are removed only when ownership can be proven." />
  <div class="summary"><div><span class="sum-icon"><Archive size={18}/></span><span><strong>2</strong><small>Owned resources</small></span></div><div><span class="sum-icon"><ShieldCheck size={18}/></span><span><strong>Healthy</strong><small>Provider status</small></span></div><div><span class="sum-icon"><Download size={18}/></span><span><strong>6.4 GB</strong><small>Simulated cache</small></span></div></div>
  <section class="history"><div class="section-head"><div><h2>Recent activity</h2><p>Sample data for the dry-run experience</p></div><button>View all</button></div>
    <div class="row"><span class="row-icon"><CheckCircle2 size={16}/></span><span class="row-copy"><strong>Omarchy ISO verified</strong><small>Download · Today at 14:28</small></span><span class="success">Complete</span><button aria-label="More actions"><MoreHorizontal size={17}/></button></div>
    <div class="row"><span class="row-icon"><CheckCircle2 size={16}/></span><span class="row-copy"><strong>Virtual machine created</strong><small>Try · Yesterday at 19:04</small></span><span class="success">Ready</span><button aria-label="More actions"><MoreHorizontal size={17}/></button></div>
  </section>
  <div class="tools"><section><FileText size={19}/><div><h2>Diagnostics</h2><p>Create a local, redacted support bundle. Preview every file before sharing.</p></div><ActionButton label="Preview bundle" secondary onClick={() => openPlan('Diagnostics bundle')} /></section><section><LifeBuoy size={19}/><div><h2>Provider health</h2><p>Check installed Try and Direct providers against the trusted catalog.</p></div><ActionButton label="Run health check" secondary onClick={() => openPlan('Provider health check')} /></section></div>
</div>

<style>
  .summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:29px}.summary>div{display:flex;align-items:center;gap:11px;padding:14px;border:1px solid var(--border);border-radius:12px;background:var(--surface)}.sum-icon{display:grid;width:34px;height:34px;place-items:center;border-radius:9px;background:rgba(255,255,255,.035);color:var(--accent)}.summary span:last-child{display:flex;flex-direction:column;gap:3px}.summary strong{color:var(--text);font-size:12px}.summary small{color:var(--text-dim);font-size:8px}.history{margin-top:13px;border:1px solid var(--border);border-radius:14px;background:var(--surface)}.section-head{display:flex;align-items:center;justify-content:space-between;padding:15px 17px;border-bottom:1px solid var(--border)}h2{margin:0;color:var(--text);font-size:12px}.section-head p,.tools p{margin:4px 0 0;color:var(--text-dim);font-size:9px;line-height:1.5}.section-head button,.row>button{border:0;background:none;color:var(--accent);font:inherit;font-size:9px;cursor:pointer}.row{display:grid;grid-template-columns:34px 1fr auto 28px;align-items:center;gap:10px;padding:12px 17px;border-bottom:1px solid var(--border)}.row:last-child{border:0}.row-icon{display:grid;width:31px;height:31px;place-items:center;border-radius:8px;background:rgba(83,190,130,.08);color:var(--success)}.row-copy{display:flex;flex-direction:column;gap:3px}.row-copy strong{color:var(--text-muted);font-size:10px}.row-copy small{color:var(--text-dim);font-size:8px}.success{color:var(--success);font-size:9px;font-weight:650}.row>button{color:var(--text-dim)}.tools{display:grid;grid-template-columns:1fr 1fr;gap:11px;margin-top:13px}.tools section{display:grid;grid-template-columns:27px 1fr;align-items:start;padding:16px;border:1px solid var(--border);border-radius:13px;background:var(--surface);color:var(--accent)}.tools section>div{min-height:77px}.tools :global(button){grid-column:1/3;width:100%}@media(max-width:650px){.summary,.tools{grid-template-columns:1fr}.row{grid-template-columns:34px 1fr auto}.row>button{display:none}}
</style>
