"""Read only two fixed partition ranges through a private userspace NBD socket.

No kernel NBD attachment or host block device exists. Fixed-newstyle negotiation
and simple READ replies follow https://github.com/NetworkBlockDevice/nbd/blob/master/doc/proto.md.
The client never implements WRITE, TRIM, resize, or arbitrary export selection.
"""
import contextlib
from pathlib import Path
import socket
import struct
import subprocess
import time

MIB = 1024**2
DISK_BYTES = 40 * 1024**3
PARTITIONS = {(MIB, 2 * 1024**3), (2 * 1024**3 + MIB, 40800092160)}


class PartitionReader:
    def __init__(self, connection, cancel):
        self.connection = connection
        self.cancel = cancel
        self.cookie = 0
        self.deadline = time.monotonic() + 1800
        magic, options, flags = struct.unpack('!QQH', self.receive(18))
        if magic != 0x4E42444D41474943 or options != 0x49484156454F5054 or not flags & 1:
            raise ValueError('Unsupported NBD handshake from local image reader')
        # FIXED_NEWSTYLE only; without NO_ZEROES, the server sends 124 padding bytes.
        connection.sendall(struct.pack('!I', 1))
        connection.sendall(struct.pack('!QII', options, 1, 0))  # empty default export name
        size, transmission = struct.unpack('!QH', self.receive(10))
        padding = self.receive(124)
        if size != DISK_BYTES or transmission & 3 != 3 or padding != bytes(124):
            raise ValueError('NBD export must be the exact read-only construction image')

    def receive(self, size):
        data = bytearray()
        deadline = min(self.deadline, time.monotonic() + 120)
        while len(data) < size:
            self.cancel()
            if time.monotonic() > deadline:
                raise TimeoutError('Local image reader timed out')
            try:
                chunk = self.connection.recv(size - len(data))
            except socket.timeout:
                continue
            if not chunk:
                raise RuntimeError('Local image reader disconnected early')
            data.extend(chunk)
        return bytes(data)

    def chunks(self, start, length):
        if (start, length) not in PARTITIONS:
            raise ValueError('Only the fixed ESP and encrypted root can be exported')
        for offset in range(start, start + length, MIB):
            self.cancel()
            size = min(MIB, start + length - offset)
            self.cookie += 1
            self.connection.sendall(struct.pack('!IHHQQI', 0x25609513, 0, 0, self.cookie, offset, size))
            magic, error, cookie = struct.unpack('!IIQ', self.receive(16))
            if magic != 0x67446698 or error or cookie != self.cookie:
                raise RuntimeError('Invalid or failed read from local construction image')
            yield self.receive(size)


@contextlib.contextmanager
def open_image(run, disk, secret_file, cancel):
    endpoint = Path('/tmp/product-export.sock')
    if endpoint.exists():
        raise ValueError('Local export socket already exists')
    # All names are generated by this recipe; image-opts never receives user text.
    command = ['qemu-nbd', '--read-only', '--persistent', '--shared=1',
               '--socket=' + str(endpoint),
               '--object', 'secret,id=product-build,file=' + str(secret_file),
               '--image-opts', 'driver=qcow2,file.driver=file,file.filename=' + str(disk)
               + ',encrypt.key-secret=product-build']
    with (run / 'export.log').open('ab') as log:
        process = subprocess.Popen(command, stdin=subprocess.DEVNULL, stdout=log, stderr=log)
        try:
            with socket.socket(socket.AF_UNIX) as connection:
                connection.settimeout(1)
                deadline = time.monotonic() + 60
                while True:
                    cancel()
                    if process.poll() is not None:
                        raise RuntimeError('Local encrypted image reader failed; see export.log')
                    try:
                        connection.connect(str(endpoint))
                        break
                    except (FileNotFoundError, ConnectionRefusedError):
                        if time.monotonic() >= deadline:
                            raise TimeoutError('Local encrypted image reader did not start')
                        time.sleep(0.1)
                reader = PartitionReader(connection, cancel)
                yield reader
                connection.sendall(struct.pack('!IHHQQI', 0x25609513, 0, 2, 0, 0, 0))  # DISC
        finally:
            if process.poll() is None:
                process.terminate()
                try:
                    process.wait(timeout=10)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait(timeout=5)
            endpoint.unlink(missing_ok=True)
