#!/usr/bin/env python3
"""Fail-closed checks inside the file-backed construction guest; never host tooling."""
import hashlib
import json
from pathlib import Path
import re
import stat
import subprocess
import uuid
from boot_menu import validate_settings


TARGET = Path('/mnt')
CIDATA = Path('/run/omarchy-cidata')
ROOT_BYTES = 40800092160


def out(*args):
    return subprocess.check_output(args, text=True).strip()


def require(condition, message):
    if not condition:
        raise RuntimeError(message)


def validate():
    require(Path('/run/archiso').is_dir(), 'This validator requires the live ISO guest')
    require(out('blockdev', '--getsize64', '/dev/vda') == '42949672960', 'Unexpected build disk')
    require(out('blockdev', '--getsize64', '/dev/vda2') == str(ROOT_BYTES), 'Root extent changed')
    lock = json.loads((CIDATA / 'product-source-lock.json').read_text())
    for path, expected in lock['installedFiles'].items():
        require(hashlib.sha256((TARGET / path).read_bytes()).hexdigest() == expected,
                'Installed upstream owner contract differs: ' + path)

    require(out('findmnt', '-n', '-o', 'FSTYPE', '/mnt') == 'btrfs', 'Root must contain Btrfs')
    source = out('findmnt', '-n', '-o', 'SOURCE', '/mnt').split('[', 1)[0]
    mapper = Path(source).resolve(strict=True)
    require(re.fullmatch(r'dm-\d+', mapper.name) is not None, 'Root is not a device mapper')
    mapping_name = Path('/sys/class/block', mapper.name, 'dm/name').read_text().strip()
    status = out('cryptsetup', 'status', mapping_name)
    require(re.search(r'^\s*type:\s+LUKS2$', status, re.M), 'Root mapping must use LUKS2')
    device = re.search(r'^\s*device:\s+(\S+)$', status, re.M)
    require(device and Path(device[1]).resolve() == Path('/dev/vda2'), 'Root mapping has a foreign backing partition')
    subprocess.run(['cryptsetup', 'isLuks', '--type', 'luks2', '/dev/vda2'], check=True)
    luks_uuid = str(uuid.UUID(out('cryptsetup', 'luksUUID', '/dev/vda2')))
    root_uuid = str(uuid.UUID(out('blkid', '-s', 'UUID', '-o', 'value', source)))
    root_guid = str(uuid.UUID(out('blkid', '-s', 'PARTUUID', '-o', 'value', '/dev/vda2')))
    luks = json.loads(out('cryptsetup', 'luksDump', '--dump-json-metadata', '/dev/vda2'))
    require(len(luks['keyslots']) == 1 and all(v['type'] == 'luks2' for v in luks['keyslots'].values()),
            'Only the fresh upstream bootstrap LUKS slot may exist')
    require(len(luks['segments']) == 1 and next(iter(luks['segments'].values()))['size'] == 'dynamic',
            'LUKS data must support growth to the target partition')

    provisioning = TARGET / 'var/lib/omarchy/provisioning'
    require((provisioning / 'pending').is_file(), 'Owner setup is not pending')
    require(not any((provisioning / p).exists() for p in ('setup-user', 'wipe-pending', 'authorized_keys')),
            'Provisioning is not a fresh ownerless install')
    require(list((provisioning / 'packages').glob('node-v*-linux-x64.tar.gz')), 'Offline owner runtime missing')
    key = provisioning / 'luks-key'
    boot_key = TARGET / 'etc/omarchy/provisioning.key'
    for path in (key, boot_key):
        info = path.lstat()
        require(stat.S_ISREG(info.st_mode) and stat.S_IMODE(info.st_mode) == 0o600 and info.st_uid == 0,
                'Bootstrap key permissions differ from upstream contract')
    # The pinned context generates token_urlsafe(24), exactly 32 ASCII bytes.
    require(re.fullmatch(rb'[A-Za-z0-9_-]{32}', key.read_bytes()) is not None,
            'Bootstrap passphrase was not generated by the pinned deferred contract')
    require(key.read_bytes() == boot_key.read_bytes(), 'Bootstrap key copies disagree')
    subprocess.run(['cryptsetup', 'open', '--test-passphrase', '--key-file', str(key), '/dev/vda2'],
                   check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    require('FILES+=(/etc/omarchy/provisioning.key)' in
            (TARGET / 'etc/mkinitcpio.conf.d/99-omarchy-provisioning-key.conf').read_text(),
            'Upstream initramfs bootstrap key drop-in missing')
    require('cryptkey=rootfs:/etc/omarchy/provisioning.key' in
            (TARGET / 'etc/limine-entry-tool.d/99-omarchy-provisioning-unlock.conf').read_text(),
            'Upstream bootstrap unlock drop-in missing')
    enabled = TARGET / 'etc/systemd/system/multi-user.target.wants/omarchy-provision-owner.service'
    require(enabled.is_symlink() and str(enabled.readlink()) == '/etc/systemd/system/omarchy-provision-owner.service',
            'Upstream owner service must be enabled')
    require(hashlib.sha256((TARGET / 'etc/systemd/system/omarchy-provision-owner.service').read_bytes()).hexdigest()
            == lock['installedFiles']['usr/share/omarchy/install/provisioning/omarchy-provision-owner.service'],
            'Enabled owner service differs from pinned upstream')

    boot_paths = [TARGET / p for p in ('etc/fstab', 'boot/limine.conf', 'etc/default/limine', 'etc/kernel/cmdline')]
    boot_paths += [p for directory in ('etc/limine-entry-tool.d', 'etc/default/limine.d')
                   for p in (TARGET / directory).glob('*.conf')]
    boot_paths += [p for p in (TARGET / 'etc').glob('crypttab*') if p.is_file()]
    for path in boot_paths:
        text = path.read_text()
        require('/dev/vda' not in text and not re.search(r'root=/dev/(?!mapper/)', text),
                'Nonportable device path in ' + str(path))
    for path in (TARGET / 'boot/limine.conf', TARGET / 'etc/kernel/cmdline'):
        text = path.read_text()
        specs = re.findall(r'cryptdevice=([^\s:]+):([^\s:"\']+)', text)
        require(specs and all(spec in ('UUID=' + luks_uuid, 'PARTUUID=' + root_guid)
                             and name == 'root' for spec, name in specs),
                'Boot entries do not unlock this installation by stable identity')
        require('root=/dev/mapper/root' in text and 'cryptkey=rootfs:/etc/omarchy/provisioning.key' in text,
                'Encrypted root and deferred bootstrap parameters missing')
    fstab = (TARGET / 'etc/fstab').read_text()
    require('UUID=' + root_uuid in fstab, 'fstab does not identify the inner Btrfs filesystem')
    ukis = list((TARGET / 'boot/EFI/Linux').glob('omarchy_*.efi'))
    require(ukis, 'Installed UKI missing')
    for uki in ukis:
        listing = out('arch-chroot', '/mnt', 'lsinitcpio', '-l', '/' + str(uki.relative_to(TARGET)))
        require('etc/omarchy/provisioning.key' in listing, 'UKI has no upstream bootstrap key')
        config = out('arch-chroot', '/mnt', 'lsinitcpio', '-c', '/' + str(uki.relative_to(TARGET)))
        hooks = re.search(r'^HOOKS=(.*)$', config, re.M)
        require(hooks and 'autodetect' not in hooks[1] and re.search(r'\bencrypt\b', hooks[1]),
                'Portable encrypted initramfs hooks missing')

    operation_data = json.loads((CIDATA / 'operation.json').read_text())
    operation = operation_data['operationId']
    boot_menu = validate_settings(operation_data['bootMenu'])
    require(json.loads((TARGET / 'etc/omarchy-boot-menu.json').read_text()) == boot_menu,
            'Installed startup settings differ from the requested settings')
    require((TARGET / 'usr/local/sbin/omarchy-boot-menu').read_bytes() == (CIDATA / 'boot_menu.py').read_bytes(),
            'Installed startup hook differs from its construction source')
    require((TARGET / 'etc/boot/hooks/post.d/85-omarchy-boot-menu').read_text() == '#!/bin/sh\nexec /usr/local/sbin/omarchy-boot-menu --apply\n',
            'Persistent startup menu hook missing')
    require((TARGET / 'etc/boot/hooks/pre.d/15-omarchy-boot-identity').read_text() == '#!/bin/sh\nexec /usr/local/sbin/omarchy-boot-menu --prepare-update\n',
            'Startup identity update hook missing')
    require(json.loads((TARGET / 'etc/omarchy-boot-identity.json').read_text()) == {
        'espPartitionGuid': str(uuid.UUID(out('blkid', '-s', 'PARTUUID', '-o', 'value', '/dev/vda1'))),
        'espFilesystemUuid': out('blkid', '-s', 'UUID', '-o', 'value', '/dev/vda1'),
    }, 'Startup menu belongs to another EFI partition')
    require(out('arch-chroot', '/mnt', 'pacman', '-Q', 'limine') == 'limine 12.6.0-1',
            'The startup menu requires the inspected Limine release')
    out('arch-chroot', '/mnt', '/usr/local/sbin/omarchy-boot-menu', '--check')
    value = {
        'bootMenu': boot_menu, 'bootMenuUpdateHook': True, 'windowsBootProtocol': 'efi_boot_entry',
        'operationId': str(uuid.UUID(operation)), 'rootFilesystemUuid': root_uuid,
        'rootLuksUuid': luks_uuid, 'espFilesystemUuid': out('blkid', '-s', 'UUID', '-o', 'value', '/dev/vda1'),
        'espPartitionGuid': str(uuid.UUID(out('blkid', '-s', 'PARTUUID', '-o', 'value', '/dev/vda1'))),
        'rootPartitionGuid': root_guid, 'package': out('arch-chroot', '/mnt', 'pacman', '-Q', 'omarchy'),
        'ownerProvisioning': 'pending', 'encryption': 'luks2', 'bootstrapKey': 'upstream-per-install',
        'ownerRekey': 'passphrase-slots-only', 'protectionState': 'owner-setup-required',
        'firstBootGrowth': 'luks-mapping-and-btrfs', 'portableInitramfs': True,
        'physicalHardwareSetup': 'upstream-on-first-boot', 'offlineRepositoryIncluded': True,
        'machineIdentity': 'generate-on-first-boot', 'buildCredentials': False,
    }
    (TARGET / 'var/lib/omarchy/direct-install/root-identity.json').write_text(json.dumps({
        'rootLuksUuid': luks_uuid, 'rootFilesystemUuid': root_uuid,
        'rootPartitionGuid': root_guid, 'sourceRootPartitionBytes': ROOT_BYTES,
    }) + '\n')
    Path('/run/omarchy-product-identity.json').write_text(json.dumps(value))


if __name__ == '__main__':
    validate()
